---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP의 새로운 릴리즈에서 새로운 기능, 향상 기능 및 버그 수정 사항이 도입되었습니다. 
---
= Cloud Volumes ONTAP 9.4의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.4에는 몇 가지 새로운 기능과 향상된 기능이 포함되어 있습니다.


NOTE: 최신 버전의 Cloud Manager에는 추가 기능과 개선 사항도 포함되어 있습니다. 를 참조하십시오 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Cloud Manager 릴리즈 노트"^] 를 참조하십시오.



== AWS GovCloud(US) 지역에서 용량제 지원

현재 Cloud Volumes ONTAP의 용량제 버전이 AWS GovCloud(US) 지역에서 지원됩니다. 이 외에도 GovCloud(US) 지역에서 Cloud Volumes ONTAP BYOL을 지원합니다.

다른 지역과 마찬가지로 GovCloud(US) 지역에 Cloud Volumes ONTAP를 구축할 수 있습니다. NetApp Cloud Central로 이동하여 GovCloud(US)에서 Cloud Manager를 실행합니다. 그런 다음 Cloud Manager에서 새로운 작업 환경을 생성하여 Cloud Volumes ONTAP PAYGO 또는 BYOL을 시작합니다.



== Cloud Volumes ONTAP 프리미엄 및 BYOL로 콜드 데이터 계층화

9.2 릴리즈에서는 성능 계층(SSD 또는 HDD)과 용량 계층(오브젝트 저장소) 간에 자동 데이터 계층화를 도입했습니다. 용량 계층으로 전송되는 콜드 데이터에는 읽기-쓰기 볼륨의 스냅샷 복사본(_Snapshot 전용_계층화 정책) 또는 대상 볼륨의 데이터(_backup_Tiering 정책)가 포함됩니다.

Cloud Volumes ONTAP 9.4 Premium 및 BYOL에서는 세 번째 옵션이 제공됩니다. 즉, _auto_Tiering 정책을 사용하여 읽기/쓰기 볼륨의 콜드 데이터 블록을 용량 계층에 계층화할 수 있습니다. 콜드 데이터에는 스냅샷 복사본뿐만 아니라 액티브 파일 시스템의 콜드 사용자 데이터도 포함됩니다.

랜덤 읽기로 읽는 경우 용량 계층의 콜드 데이터 블록이 핫 상태가 되어 성능 계층으로 이동합니다. 인덱스 및 바이러스 백신 검사와 관련된 읽기 작업을 순차적으로 수행할 경우 콜드 데이터 블록이 콜드 상태를 유지하고 성능 계층으로 이동하지 않습니다.

Cloud Manager에서 볼륨을 생성하거나 편집할 때 계층화 정책을 선택할 수 있습니다. 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-tiering.html["Cloud Manager 설명서"].



== Microsoft Azure의 데이터 계층화

이제 핫 데이터(프리미엄 또는 표준 관리 디스크)의 성능 계층과 콜드 데이터(Azure Blob 스토리지)의 용량 계층을 결합하여 Azure 스토리지 비용을 절감할 수 있습니다. AWS에서 지원되는 것과 동일한 계층화 정책은 Azure에서 자동, 스냅샷 전용 및 백업도 지원됩니다.


NOTE: 데이터 계층화는 DS3_v2 가상 머신 유형에서 지원되지 않습니다.

Cloud Manager에서 볼륨을 생성하거나 편집할 때 계층화 정책을 선택할 수 있습니다. 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-tiering.html["Cloud Manager 설명서"].



== 프로비저닝된 IOPS SSD를 사용한 데이터 계층화

이제 데이터 계층화가 프로비저닝된 IOPS SSD가 있는 AWS에서 지원됩니다. 이러한 SSD를 핫 데이터의 성능 계층으로 사용하고 Amazon S3를 콜드 데이터의 용량 계층으로 사용할 수 있습니다.



== 데이터를 계층화할 때 성능 향상

9.2 및 9.3 릴리즈에서 도입된 향상된 쓰기 성능은 이제 콜드 데이터를 오브젝트 저장소 용량 계층으로 계층화하는 볼륨에서 지원됩니다. 이는 Cloud Volumes ONTAP 9.4에서 새로운 SSD 애그리게이트에서 생성된 볼륨에 적용됩니다.



== AWS의 여러 워크로드 성능 향상

Cloud Volumes ONTAP은 이제 AWS에 추가 네트워킹 대역폭을 제공하여 다양한 워크로드가 있는 시스템의 성능을 향상합니다. 9.4로 업그레이드하고 새로운 9.4 시스템을 시작할 때 다음과 같은 EC2 인스턴스 유형에 대해 추가 대역폭을 사용할 수 있습니다.

* M4.xLarge
* m4.2xLarge
* m4.4xLarge
* c4.4xLarge
* c4.8xLarge




== EC2 인스턴스 유형은 더 이상 지원되지 않습니다

모든 버전의 Cloud Volumes ONTAP에서는 더 이상 여러 EC2 인스턴스 유형을 지원하지 않습니다. 이러한 인스턴스 유형을 실행 중인 기존 시스템은 계속 정상적으로 작동하지만 다른 인스턴스 유형으로 변경하는 것이 좋습니다.

인스턴스 유형과 NetApp 라이센스 간의 가격 차이를 검토하려면 의 AWS Marketplace를 방문하십시오 http://aws.amazon.com/marketplace/pp/B011KEZ734["단일 노드 시스템"^] 및 용 http://aws.amazon.com/marketplace/pp/B01H4LVJ84["HA 쌍"^].

[cols="2*"]
|===
| 인스턴스 유형이 더 이상 지원되지 않습니다 | 권장 인스턴스 유형입니다 


| c3.2xLarge | M4.xLarge 


| c4.2xLarge | m4.2xLarge 


| M3.xLarge | M4.xLarge 


| m3.2xLarge | m4.2xLarge 


| R3.xLarge | m4.2xLarge 


| r3.2xLarge | r4.2xLarge 
|===

TIP: 데이터 계층화 및 향상된 성능에서는 M3 및 R3 인스턴스 유형이 지원되지 않으므로 M4 및 R4 인스턴스 유형으로 이동하면 이러한 Cloud Volumes ONTAP 기능을 활용할 수 있습니다.



== 노트 업그레이드

* Cloud Volumes ONTAP 업그레이드는 Cloud Manager에서 완료해야 합니다. System Manager 또는 CLI를 사용하여 Cloud Volumes ONTAP를 업그레이드해서는 안 됩니다. 이렇게 하면 시스템 안정성에 영향을 줄 수 있습니다.
* 9.3 릴리즈에서 Cloud Volumes ONTAP 9.4로 업그레이드할 수 있습니다.
+
버전 요구 사항에 대한 자세한 내용은 을 참조하십시오 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-dot-upgrade/GUID-AC0EB781-583F-4C90-A4C4-BC7B14CEFD39.html["ONTAP 9 설명서: 클러스터 업데이트 요구 사항"^].

* 단일 노드 시스템을 업그레이드하면 시스템이 최대 25분 동안 오프라인 상태로 전환되고 이 동안 I/O가 중단됩니다.
* HA 2노드 업그레이드는 무중단으로 I/O를 업그레이드할 수 있으며 이 무중단 업그레이드 프로세스 중에 각 노드가 동시 업그레이드되어 클라이언트에 I/O를 계속 제공합니다.

